# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QuCrkAJKI0eiM5L_rCpU6_W5YjtfYCMA
"""

!pip install sendgrid

import os
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

SENDGRID_API_KEY="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"

message = Mail(
    from_email='dhrumildma@gmail.com',
    to_emails='abve9575@colorado.edu',
    subject='Sending with Twilio SendGrid is Fun',
    html_content='<strong>and easy to do anywhere, even with Python</strong>')
try:
    sg = SendGridAPIClient(SENDGRID_API_KEY)
    response = sg.send(message)
    print(response.status_code)
    print(response.body)
    print(response.headers)
except Exception as e:
    print(e)